// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/search.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SemanticEmbeddingService_Search_FullMethodName = "/search.SemanticEmbeddingService/Search"
)

// SemanticEmbeddingServiceClient is the client API for SemanticEmbeddingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SemanticSearchService provides helper functions for semantic search.
type SemanticEmbeddingServiceClient interface {
	// Search returns the most relevant documents for the given query.
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type semanticEmbeddingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSemanticEmbeddingServiceClient(cc grpc.ClientConnInterface) SemanticEmbeddingServiceClient {
	return &semanticEmbeddingServiceClient{cc}
}

func (c *semanticEmbeddingServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, SemanticEmbeddingService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SemanticEmbeddingServiceServer is the server API for SemanticEmbeddingService service.
// All implementations must embed UnimplementedSemanticEmbeddingServiceServer
// for forward compatibility.
//
// SemanticSearchService provides helper functions for semantic search.
type SemanticEmbeddingServiceServer interface {
	// Search returns the most relevant documents for the given query.
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedSemanticEmbeddingServiceServer()
}

// UnimplementedSemanticEmbeddingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSemanticEmbeddingServiceServer struct{}

func (UnimplementedSemanticEmbeddingServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedSemanticEmbeddingServiceServer) mustEmbedUnimplementedSemanticEmbeddingServiceServer() {
}
func (UnimplementedSemanticEmbeddingServiceServer) testEmbeddedByValue() {}

// UnsafeSemanticEmbeddingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SemanticEmbeddingServiceServer will
// result in compilation errors.
type UnsafeSemanticEmbeddingServiceServer interface {
	mustEmbedUnimplementedSemanticEmbeddingServiceServer()
}

func RegisterSemanticEmbeddingServiceServer(s grpc.ServiceRegistrar, srv SemanticEmbeddingServiceServer) {
	// If the following call panics, it indicates UnimplementedSemanticEmbeddingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SemanticEmbeddingService_ServiceDesc, srv)
}

func _SemanticEmbeddingService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticEmbeddingServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticEmbeddingService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticEmbeddingServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SemanticEmbeddingService_ServiceDesc is the grpc.ServiceDesc for SemanticEmbeddingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SemanticEmbeddingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search.SemanticEmbeddingService",
	HandlerType: (*SemanticEmbeddingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SemanticEmbeddingService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/search.proto",
}
